In [8]:
"""
데이터 불균형 : 클래스가 어느 한 쪽으로만 일방적으로 존재
해결 방법
1) 오버 샘플링 : 클래스가 적은 쪽의 데이터를 랜덤 복원 샘플링하여 복사 붙여넣기를 반복하여 두 클래스의 비율이
비슷하게 함
2) 언더 샘플링 : 클래스가 많은 쪽의 데이터를 랜덤 샘플링하여 삭제하기를 반복하여 두 클래스의 비율이
비슷하게 함
3) 오버 & 언더 샘플링 
ex) Y:1000건 vs N:10건 => 1010 / 2 = 505, Y는 505건이 될때까지 언더샘플링, N은 505건이 될때까지 오버샘플링
4) SMOTE 알고리즘
기존 데이터를 적절하게 혼합하여 새로운 데이터를 생성하는 방법

"""

'\n데이터 불균형 : 클래스가 어느 한 쪽으로만 일방적으로 존재\n해결 방법\n1) 오버 샘플링 : 클래스가 적은 쪽의 데이터를 랜덤 복원 샘플링하여 복사 붙여넣기를 반복하여 두 클래스의 비율이\n비슷하게 함\n2) 언더 샘플링 : 클래스가 많은 쪽의 데이터를 랜덤 샘플링하여 삭제하기를 반복하여 두 클래스의 비율이\n비슷하게 함\n3) 오버 & 언더 샘플링 \nex) Y:1000건 vs N:10건 => 1010 / 2 = 505, Y는 505건이 될때까지 언더샘플링, N은 505건이 될때까지 오버샘플링\n4) SMOTE 알고리즘\n기존 데이터를 적절하게 혼합하여 새로운 데이터를 생성하는 방법\n\n'

In [9]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt

In [10]:
card_df = pd.read_csv('creditcard.csv')
card_df.head(3)

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  

[3 rows x 31 columns]

In [30]:
from sklearn.model_selection import train_test_split

In [31]:
x_features=card_df.iloc[:,:-1] #x, 284807 rows × 30 columns
y_target=card_df.iloc[:,-1] #y, Length: 284807

In [15]:
xtrain, xtest, ytrain, ytest=train_test_split(x_features, y_target, 
                 test_size=0.3, random_state=20231023, stratify=y_target)

In [32]:
ytrain.value_counts()

0    199020
1       344
Name: Class, dtype: int64

In [33]:
ytest.value_counts()

0    85295
1      148
Name: Class, dtype: int64

In [34]:
def get_preprocessed_df(df=None):
    df_copy = df.copy()
    df_copy.drop('Time', axis=1, inplace=True)
    return df_copy

In [35]:
df_copy=get_preprocessed_df(card_df)

In [36]:
df_copy

V1         V2        V3        V4        V5        V6  \
0       -1.359807  -0.072781  2.536347  1.378155 -0.338321  0.462388   
1        1.191857   0.266151  0.166480  0.448154  0.060018 -0.082361   
2       -1.358354  -1.340163  1.773209  0.379780 -0.503198  1.800499   
3       -0.966272  -0.185226  1.792993 -0.863291 -0.010309  1.247203   
4       -1.158233   0.877737  1.548718  0.403034 -0.407193  0.095921   
...           ...        ...       ...       ...       ...       ...   
284802 -11.881118  10.071785 -9.834783 -2.066656 -5.364473 -2.606837   
284803  -0.732789  -0.055080  2.035030 -0.738589  0.868229  1.058415   
284804   1.919565  -0.301254 -3.249640 -0.557828  2.630515  3.031260   
284805  -0.240440   0.530483  0.702510  0.689799 -0.377961  0.623708   
284806  -0.533413  -0.189733  0.703337 -0.506271 -0.012546 -0.649617   

              V7        V8        V9       V10  ...       V21       V22  \
0       0.239599  0.098698  0.363787  0.090794  ... -0.018307  0.277838   
1      -0.078803  0.085102 -0.255425 -0.166974  ... -0.225775 -0.638672   
2       0.791461  0.247676 -1.514654  0.207643  ...  0.247998  0.771679   
3       0.237609  0.377436 -1.387024 -0.054952  ... -0.108300  0.005274   
4       0.592941 -0.270533  0.817739  0.753074  ... -0.009431  0.798278   
...          ...       ...       ...       ...  ...       ...       ...   
284802 -4.918215  7.305334  1.914428  4.356170  ...  0.213454  0.111864   
284803  0.024330  0.294869  0.584800 -0.975926  ...  0.214205  0.924384   
284804 -0.296827  0.708417  0.432454 -0.484782  ...  0.232045  0.578229   
284805 -0.686180  0.679145  0.392087 -0.399126  ...  0.265245  0.800049   
284806  1.577006 -0.414650  0.486180 -0.915427  ...  0.261057  0.643078   

             V23       V24       V25       V26       V27       V28  Amount  \
0      -0.110474  0.066928  0.128539 -0.189115  0.133558 -0.021053  149.62   
1       0.101288 -0.339846  0.167170  0.125895 -0.008983  0.014724    2.69   
2       0.909412 -0.689281 -0.327642 -0.139097 -0.055353 -0.059752  378.66   
3      -0.190321 -1.175575  0.647376 -0.221929  0.062723  0.061458  123.50   
4      -0.137458  0.141267 -0.206010  0.502292  0.219422  0.215153   69.99   
...          ...       ...       ...       ...       ...       ...     ...   
284802  1.014480 -0.509348  1.436807  0.250034  0.943651  0.823731    0.77   
284803  0.012463 -1.016226 -0.606624 -0.395255  0.068472 -0.053527   24.79   
284804 -0.037501  0.640134  0.265745 -0.087371  0.004455 -0.026561   67.88   
284805 -0.163298  0.123205 -0.569159  0.546668  0.108821  0.104533   10.00   
284806  0.376777  0.008797 -0.473649 -0.818267 -0.002415  0.013649  217.00   

        Class  
0           0  
1           0  
2           0  
3           0  
4           0  
...       ...  
284802      0  
284803      0  
284804      0  
284805      0  
284806      0  

[284807 rows x 30 columns]

In [37]:
def get_train_test_dataset(df=None):
    df_copy = get_preprocessed_df(df)
    X_features = df_copy.iloc[:, :-1]
    y_target = df_copy.iloc[:, -1]
    X_train, X_test, y_train, y_test = \
    train_test_split(X_features, y_target, test_size=0.3, random_state=0, stratify=y_target)
    return X_train, X_test, y_train, y_test

X_train, X_test, y_train, y_test = get_train_test_dataset(card_df)

In [45]:
X_train.head()
X_test.head()
y_train.head()
y_test.head()
X_train.shape #(199364, 29)
X_test.shape #(85443, 29)

(85443, 29)

In [46]:
print(y_train.value_counts()/y_train.shape[0] * 100)


0    99.827451
1     0.172549
Name: Class, dtype: float64


In [23]:
print(y_test.value_counts()/y_test.shape[0] * 100)

0    99.826785
1     0.173215
Name: Class, dtype: float64


In [24]:
from sklearn.linear_model import LogisticRegression

In [25]:
lr_clf=LogisticRegression()

In [26]:
lr_clf.fit(X_train, y_train)

C:\Users\user\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [27]:
lr_clf.predict(X_test)

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [28]:
lr_clf.predict(X_test)
pd.Series(lr_clf.predict(X_test)).value_counts()

0    85341
1      102
dtype: int64

In [47]:
lr_clf.predict_proba(X_test)
lr_clf.predict_proba(X_test)

array([[9.98651690e-01, 1.34831002e-03],
       [9.99876546e-01, 1.23454097e-04],
       [9.99808217e-01, 1.91783045e-04],
       ...,
       [9.99753313e-01, 2.46686772e-04],
       [9.99253336e-01, 7.46664288e-04],
       [9.99865249e-01, 1.34751489e-04]])

In [48]:
pip install lightgbm

Note: you may need to restart the kernel to use updated packages.


In [49]:
from lightgbm import LGBMClassifier

In [50]:
lgbm_clf=LGBMClassifier(n_estimators=1000, num_leaves=64, boost_from_average=False)
#boost_from_average 는 데이터가 불균형 분포되어 있을때 false

In [51]:
lgbm_clf.fit(X_train, y_train)

[LightGBM] [Info] Number of positive: 344, number of negative: 199020
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.015244 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 7395
[LightGBM] [Info] Number of data points in the train set: 199364, number of used features: 29
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits w

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No f

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No f

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No f

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No f

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No f

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No f

LGBMClassifier(boost_from_average=False, n_estimators=1000, num_leaves=64)

In [53]:
pred=lgbm_clf.predict(X_test)
pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [54]:
lgbm_clf.predict_proba(X_test)

array([[9.99999997e-01, 3.49830240e-09],
       [1.00000000e+00, 1.08517297e-10],
       [1.00000000e+00, 2.23232317e-10],
       ...,
       [9.99999996e-01, 3.66393546e-09],
       [9.99999999e-01, 6.63996306e-10],
       [1.00000000e+00, 1.08138237e-10]])

In [56]:
X_train.head()

V1        V2        V3        V4        V5        V6        V7  \
211605 -8.367621  7.402969 -5.114191 -2.966792 -0.985904 -1.660018  0.397816   
231628 -1.290662  0.764452 -0.169233 -1.688528  1.984718 -0.717210  1.667635   
110643 -0.606860  0.233923  2.633361 -0.155762 -0.328850 -0.070593  0.173023   
11478   1.374168 -0.330389  0.812971 -0.183112 -1.074771 -0.933788 -0.544238   
243724 -2.146505 -7.603113 -4.928224  1.449173 -2.083871 -0.984759  3.629816   

              V8        V9       V10  ...       V20       V21       V22  \
211605  1.008250  5.290976  9.315735  ...  3.589299 -0.557927  0.349087   
231628 -0.228295 -0.959071 -0.679429  ...  0.057620  0.138615  0.390374   
110643  0.113394  0.680147 -0.686651  ... -0.129287  0.007393  0.265045   
11478  -0.348237  0.614925  0.080408  ...  0.078163 -0.134742  0.016793   
243724 -1.302973 -1.434148 -0.021909  ...  4.009181  1.274986 -0.857670   

             V23       V24       V25       V26       V27       V28   Amount  
211605  0.301734  0.662330  1.145939 -0.012273  1.513736  0.669504     0.69  
231628 -0.678774  0.292254  1.425865  0.265341  0.051405  0.103879    55.47  
110643 -0.040615  0.406088 -0.498823  0.121851 -0.046840 -0.087259    11.50  
11478   0.002610  0.714527  0.536175 -0.307487 -0.003555  0.013024    10.00  
243724 -2.109682  0.169338 -0.322888  0.777822 -0.552258  0.304777  2290.05  

[5 rows x 29 columns]

In [57]:
X_train.describe()

V1             V2             V3             V4  \
count  199364.000000  199364.000000  199364.000000  199364.000000   
mean        0.000386      -0.000637       0.000587      -0.001239   
std         1.959976       1.658734       1.512912       1.413217   
min       -56.407510     -72.715728     -32.965346      -5.683171   
25%        -0.921490      -0.598848      -0.889918      -0.849806   
50%         0.015893       0.065727       0.180635      -0.019842   
75%         1.316633       0.804333       1.028314       0.744065   
max         2.454930      22.057729       9.382558      16.875344   

                  V5             V6             V7             V8  \
count  199364.000000  199364.000000  199364.000000  199364.000000   
mean        0.000596       0.000806      -0.000127       0.001900   
std         1.362707       1.322962       1.216585       1.191216   
min       -35.182120     -26.160506     -43.557242     -73.216718   
25%        -0.690631      -0.767513      -0.556268      -0.207917   
50%        -0.054758      -0.273142       0.040109       0.023008   
75%         0.609794       0.400874       0.570132       0.327720   
max        34.801666      21.550496      36.877368      20.007208   

                  V9            V10  ...            V20            V21  \
count  199364.000000  199364.000000  ...  199364.000000  199364.000000   
mean        0.000387      -0.000203  ...       0.000546       0.001181   
std         1.098032       1.086637  ...       0.774205       0.736703   
min       -13.434066     -24.588262  ...     -28.009635     -34.830382   
25%        -0.642713      -0.535148  ...      -0.211459      -0.227817   
50%        -0.050546      -0.091521  ...      -0.062514      -0.028990   
75%         0.597585       0.456096  ...       0.133886       0.186863   
max        15.594995      23.745136  ...      39.420904      27.202839   

                 V22            V23            V24            V25  \
count  199364.000000  199364.000000  199364.000000  199364.000000   
mean        0.000770      -0.000907       0.000708       0.000160   
std         0.724805       0.630090       0.605543       0.520830   
min       -10.933144     -44.807735      -2.836627     -10.295397   
25%        -0.540206      -0.162056      -0.353481      -0.317180   
50%         0.007585      -0.011301       0.041293       0.016244   
75%         0.529286       0.147035       0.440205       0.351141   
max        10.503090      22.528412       4.022866       6.070850   

                 V26            V27            V28         Amount  
count  199364.000000  199364.000000  199364.000000  199364.000000  
mean       -0.001173      -0.000476       0.000252      88.286313  
std         0.482453       0.401370       0.330830     248.033917  
min        -2.604551     -22.565679     -11.710896       0.000000  
25%        -0.328089      -0.070961      -0.053200       5.640000  
50%        -0.053516       0.001207       0.011043      22.000000  
75%         0.240123       0.090888       0.078216      77.000000  
max         3.463246      12.152401      33.847808   19656.530000  

[8 rows x 29 columns]

In [58]:
import numpy as np

array([-8.36762104, -1.29066221, -0.60686021, ...,  0.82782046,
       -1.52390327, -1.60856031])

In [63]:
#이상치 제거
q25=np.percentile(X_train['V1'].values, 25)
q75=np.percentile(X_train['V1'].values, 75)
iqr=q75-q25
iqr15=iqr*1.5
#표준화

In [64]:
lowest_val=q25-iqr15 #하한 바운더리
highest_val=q75+iqr15#상한 바운더리

In [73]:
X_train['V1'][(X_train['V1']<lowest_val) | (X_train['V1']>highest_val)].index

Int64Index([211605, 151631,  76190, 207772, 220170, 109519, 166031, 283347,
             18527, 259701,
            ...
            222507,  72745,  20946,  77564, 169338, 125442, 264145, 216442,
             20260,  19760],
           dtype='int64', length=4928)

In [ ]:
#타이타닉

In [ ]:
#SMOTE 오버샘플링

In [74]:
pip install -U imbalanced-learn

Note: you may need to restart the kernel to use updated packages.


In [75]:
from imblearn.over_sampling import SMOTE

In [76]:
smote=SMOTE(random_state=0)

In [77]:
X_train_over, y_train_over=smote.fit_resample(X_train, y_train)

In [80]:
X_train.shape

(199364, 29)

In [81]:
X_train_over.shape

(398040, 29)

In [84]:
pd.Series(y_train_over).value_counts()

0    199020
1    199020
Name: Class, dtype: int64

In [85]:
lr_clf=LogisticRegression()

In [86]:
lr_clf.fit(X_train_over, y_train_over)

C:\Users\user\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [87]:
lr_clf.predict(X_test)

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [88]:
import numpy as np

from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression

from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score


In [92]:
cancer_data=load_breast_cancer()
cancer_data
X_data=cancer_data.data
y_label=cancer_data.target

In [94]:
np.shape(X_data) #(569, 30)

(569, 30)

In [95]:
X_train, X_test, y_train,y_test=train_test_split(X_data, y_label,
                                                 test_size=0.2, 
                                                 random_state=20231024)

In [97]:
#스태킹(stacking)
#기본모델(knn, rf, dt, adaboost)
knn_clf=KNeighborsClassifier(n_neighbors=5)
rf_clf=RandomForestClassifier(n_estimators=100, random_state=42)
dt_clf=DecisionTreeClassifier()
ada_clf=AdaBoostClassifier(n_estimators=100)

In [98]:
knn_clf.fit(X_train, y_train)
rf_clf.fit(X_train, y_train)
dt_clf.fit(X_train, y_train)
ada_clf.fit(X_train, y_train)

AdaBoostClassifier(n_estimators=100)

In [99]:
knn_pred=knn_clf.predict(X_test)
rf_pred=rf_clf.predict(X_test)
dt_pred=dt_clf.predict(X_test)
ada_pred=ada_clf.predict(X_test)

In [100]:
print(accuracy_score(y_test, knn_pred))
print(accuracy_score(y_test, rf_pred))
print(accuracy_score(y_test, dt_pred))
print(accuracy_score(y_test, ada_pred))

0.9298245614035088
0.9473684210526315
0.9473684210526315
0.9736842105263158


In [106]:
knn_pred.shape #(114,)

(114,)

In [110]:
pred=np.array([knn_pred,rf_pred,dt_pred,ada_pred])#(114,) => (4,114)
pred.shape

(4, 114)

In [111]:
pred=np.transpose(pred)
pred #114,4

array([[1, 1, 1, 1],
       [0, 0, 0, 0],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 1, 1, 1],
       [0, 0, 0, 0],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [0, 0, 0, 0],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 1, 1, 1],
       [0, 0, 0, 0],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 1, 1, 1],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [0, 1, 1, 1],
       [0, 0, 0, 0],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1,

In [112]:
#최종 스태킹 모델 : 로지스틱 회귀

In [113]:
lr_final=LogisticRegression()

In [115]:
lr_final.fit(pred, y_test)

LogisticRegression()

In [116]:
final=lr_final.predict(pred)
final

array([1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 1])

In [117]:
accuracy_score(final, y_test)

0.9649122807017544

In [118]:
#연관규칙

In [119]:
dataset=[['사과','치즈','생수'],
['생수','호두','치즈','고등어'],
['수박','사과','생수'],
['생수','호두','치즈','옥수수']]

In [121]:
pip install mlxtend

  Obtaining dependency information for mlxtend from https://files.pythonhosted.org/packages/73/da/d5d77a9a7a135c948dbf8d3b873655b105a152d69e590150c83d23c3d070/mlxtend-0.23.0-py3-none-any.whl.metadata
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   --------- ------------------------------ 0.3/1.4 MB 7.0 MB/s eta 0:00:01
   --------------------- ------------------ 0.8/1.4 MB 8.1 MB/s eta 0:00:01
   ---------------------------------------  1.4/1.4 MB 11.5 MB/s eta 0:00:01
   ---------------------------------------- 1.4/1.4 MB 9.2 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [122]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

In [ ]:
dataset=[['사과','치즈','생수'],
['생수','호두','치즈','고등어'],
['수박','사과','생수'],
['생수','호두','치즈','옥수수']]

In [123]:
te=TransactionEncoder()

In [124]:
te_ary=te.fit(dataset).transform(dataset)

In [128]:
te_ary
df=pd.DataFrame(te_ary, columns=te.columns_)
df

고등어     사과    생수     수박    옥수수     치즈     호두
0  False   True  True  False  False   True  False
1   True  False  True  False  False   True   True
2  False   True  True   True  False  False  False
3  False  False  True  False   True   True   True

In [127]:
te.columns_

['고등어', '사과', '생수', '수박', '옥수수', '치즈', '호두']

In [135]:
type(apriori(df, min_support=0.5, use_colnames=True))

pandas.core.frame.DataFrame

In [137]:
freq_itemsets=apriori(df, min_support=0.5, use_colnames=True)

In [138]:
freq_itemsets

support      itemsets
0     0.50          (사과)
1     1.00          (생수)
2     0.75          (치즈)
3     0.50          (호두)
4     0.50      (사과, 생수)
5     0.75      (치즈, 생수)
6     0.50      (호두, 생수)
7     0.50      (호두, 치즈)
8     0.50  (호두, 치즈, 생수)

In [143]:
res=association_rules(freq_itemsets, metric='lift')
res[res['lift']>1]

antecedents consequents  antecedent support  consequent support  support  \
6         (호두)        (치즈)                0.50                0.75      0.5   
7         (치즈)        (호두)                0.75                0.50      0.5   
9     (호두, 생수)        (치즈)                0.50                0.75      0.5   
10    (치즈, 생수)        (호두)                0.75                0.50      0.5   
11        (호두)    (치즈, 생수)                0.50                0.75      0.5   
12        (치즈)    (호두, 생수)                0.75                0.50      0.5   

    confidence      lift  leverage  conviction  zhangs_metric  
6     1.000000  1.333333     0.125         inf            0.5  
7     0.666667  1.333333     0.125         1.5            1.0  
9     1.000000  1.333333     0.125         inf            0.5  
10    0.666667  1.333333     0.125         1.5            1.0  
11    1.000000  1.333333     0.125         inf            0.5  
12    0.666667  1.333333     0.125         1.5            1.0

In [ ]:
맥주 -> 땅콩   lift=10

In [144]:
dataset = [['Milk', 'Onion', 'Nutmeg', 'Eggs', 'Yogurt'],
           ['Onion', 'Nutmeg', 'Eggs', 'Yogurt'],
           ['Milk', 'Apple', 'Eggs'],
           ['Milk', 'Unicorn', 'Corn', 'Yogurt'],
           ['Corn', 'Onion', 'Onion', 'Ice cream', 'Eggs']]

In [ ]:
"""
연습문제

마트의 데이터분석가 
 - 번들, 유통, 대체 등
 =>카페 제출

"""