In [3]:
for num in range(10) :
    print(float(num / 10))

0.0
0.1
0.2
0.3
0.4
0.5
0.6
0.7
0.8
0.9


In [ ]:
def f():
    
    return

x=f()
print("hi")

In [ ]:
"""
넘파이
-배열 프로그래밍(대규모 데이터를 빠르게 연산)
-파이썬 리스트:속도 느림, 메모리 많이 차지
-넘파이(수치연산 패키지) 배열 : 빠름, 적게차지, 배열 요소 타입이 모두 동일, 
원소의 갯수가 변경 안됨


판다스

맷플랏립, 플랏리, 태블로, 씨본 등
"""

In [4]:
import numpy as np

In [7]:
ar=np.array([1.1,2,3])
ar

array([1.1, 2. , 3. ])

In [8]:
type(ar)

numpy.ndarray

In [9]:
myarr=np.arange(1000000)
mylist=list(np.arange(1000000))

In [15]:
list(np.arange(10))
myarr
#print(mylist)

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [16]:
%timeit myarr2=myarr*2
%timeit mylist2=[x*2 for x in mylist]

1.08 ms ± 27.1 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
63.9 ms ± 638 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [23]:
myarr=np.arange(100000000)
mylist=list(np.arange(100000000))

In [28]:
myarr

array([       0,        1,        2, ..., 99999997, 99999998, 99999999])

In [29]:
[1,2,3]*2

[1, 2, 3, 1, 2, 3]

In [25]:
mylist3=[x*2 for x in mylist]

In [26]:
myarr3

array([        0,         2,         4, ..., 199999994, 199999996,
       199999998])

In [27]:
mylist3

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198,
 200,
 202,
 204,
 206,
 208,
 210,
 212,
 214,
 216,
 218,
 220,
 222,
 224,
 226,
 228,
 230,
 232,
 234,
 236,
 238,
 240,
 242,
 244,
 246,
 248,
 250,
 252,
 254,
 256,
 258,
 260,
 262,
 264,
 266,
 268,
 270,
 272,
 274,
 276,
 278,
 280,
 282,
 284,
 286,
 288,
 290,
 292,
 294,
 296,
 298,
 300,
 302,
 304,
 306,
 308,
 310,
 312,
 314,
 316,
 318,
 320,
 322,
 324,
 326,
 328,
 330,
 332,
 334,
 336,
 338,
 340,
 342,
 344,
 346,
 348,
 350,

In [30]:
data=np.array([[1,-0.1,2], [0,-3,6]])
data

array([[ 1. , -0.1,  2. ],
       [ 0. , -3. ,  6. ]])

In [31]:
data*2

array([[ 2. , -0.2,  4. ],
       [ 0. , -6. , 12. ]])

In [32]:
data+data

array([[ 2. , -0.2,  4. ],
       [ 0. , -6. , 12. ]])

In [37]:
list(data+data)

[array([ 2. , -0.2,  4. ]), array([ 0., -6., 12.])]

In [40]:
arr=np.array([1,2,3])
arr.ndim
arr.dtype

dtype('int32')

In [42]:
arr

array([1, 2, 3])

In [44]:
arr*3+1

array([ 4,  7, 10])

In [47]:
arr

array([1, 2, 3])

In [48]:
arr==2

array([False,  True, False])

In [49]:
arr>2

array([False, False,  True])

In [50]:
(arr==2 ) | (arr>2)

array([False,  True,  True])

In [51]:
arr.dtype

dtype('int32')

In [53]:
type(arr)

numpy.ndarray

In [56]:
np.zeros(10)
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [58]:
np.ones(10)
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [59]:
np.ones(10)*2

array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [60]:
arr

array([1, 2, 3])

In [61]:
arr2=np.ones(3)
arr2

array([1., 1., 1.])

In [63]:
arr+arr2
arr*arr2

array([1., 2., 3.])

In [66]:
arr1=arr.astype(np.float64)
arr1
arr1.dtype

dtype('float64')

In [68]:
arr1=arr1.astype(np.int32)
arr1

array([1, 2, 3])

In [69]:
arr1.astype(float)

array([1., 2., 3.])

In [70]:
arr

array([1, 2, 3])

In [71]:
arr2

array([1., 1., 1.])

In [72]:
arr>arr2

array([False,  True,  True])

In [73]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
arr[5:8]=100
arr

array([  0,   1,   2,   3,   4, 100, 100, 100,   8,   9])

In [76]:
hund=arr[5:8]
hund

array([100, 100, 100])

In [77]:
arr[1]=999
arr

array([  0, 999,   2,   3,   4, 100, 100, 100,   8,   9])

In [78]:
arr

array([  0, 999,   2,   3,   4, 100, 100, 100,   8,   9])

In [79]:
arr=1

In [80]:
arr

1

In [81]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
arr[:]=10
arr

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [85]:
arr2d=np.arange(1,10).reshape(3,3)
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [89]:
arr2d[1]
arr2d[1][0]
arr2d[1,0]

4

In [93]:
#1~12 까지 값으로 3행 4열 생성, 10을 참조
arr=np.arange(1,13).reshape(3,4)
arr[2][1]

10

In [95]:
arr
len(arr)

3

In [97]:
len(arr[0])

4

In [102]:
d=np.arange(1,25).reshape(2,3,4)
d
#3차원 배열 (깊이(차원), 행, 열)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [107]:
len(d)
len(d[0])
len(d[0][0])
d.ndim #3차원
d.shape

(2, 3, 4)

In [108]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [111]:
np.sum(arr)
np.sum(arr,axis=0)
np.sum(arr,axis=1)

array([10, 26, 42])

In [112]:
d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [114]:
np.sum(d)
np.sum(d,axis=0) #차원(축)을 기준으로 합계

array([[14, 16, 18, 20],
       [22, 24, 26, 28],
       [30, 32, 34, 36]])

In [115]:
np.sum(d,axis=1) #행 기준으로 합계

array([[15, 18, 21, 24],
       [51, 54, 57, 60]])

In [116]:
np.sum(d,axis=2) #열 기준으로 합계

array([[10, 26, 42],
       [58, 74, 90]])

In [117]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [121]:
arr[2]
arr[-1]
arr[-1,-1]

12

In [126]:
arr[0]
arr[0,:]
arr[:,1]
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [134]:
arr[:,2]
arr[1,2:] #arr[1,2:4]
arr[2,0:2]
arr[2,:2]

array([ 9, 10])

In [135]:
a=np.array([1,2,3])
b=np.array([True,False,True])

In [137]:
#불린참조:True에 해당되는 자료를 참조
a
#b에 저장된 값이 True인 위치의 a배열 요소값을 참조
a[b]

array([1, 3])

In [138]:
#kaggle.com 가입
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [141]:
#arr배열에서 4의 배수만 추출
arr%4==0
arr[arr%4==0]

array([ 4,  8, 12])

In [142]:
a=np.arange(11,20)
a

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [144]:
a[np.array([0,3,5])]
a[np.array([0,3,5,5,5,5,5,5,5])]

array([11, 14, 16, 16, 16, 16, 16, 16, 16])

In [145]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [149]:
arr[[2,0,1],:]

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [147]:
arr[:,[True, False, True, False]]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [150]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [151]:
brr=arr

In [152]:
brr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [154]:
arr[1,0]=50

In [156]:
arr
brr

array([[ 1,  2,  3,  4],
       [50,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [157]:
crr=arr.copy()
crr

array([[ 1,  2,  3,  4],
       [50,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [160]:
arr[2,0]=90

In [161]:
crr

array([[ 1,  2,  3,  4],
       [50,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [162]:
arr

array([[ 1,  2,  3,  4],
       [50,  6,  7,  8],
       [90, 10, 11, 12]])

In [163]:
names=np.array(['Kim',"Park","Lee"])
data=np.array([[4,2],[0,2],[-1,2]])

In [167]:
names=="Kim"
data[names=="Kim"]
data[names=="Kim",1]

array([2])

In [171]:
names
data[names != "Park"]
data[names != "Park", 0]

array([ 4, -1])

In [175]:
~(names=="Kim")
data[~(names=="Kim")]

array([[ 0,  2],
       [-1,  2]])

In [179]:
names
data[(names=="Park") | (names=="Lee")]

array([[ 0,  2],
       [-1,  2]])

In [180]:
data

array([[ 4,  2],
       [ 0,  2],
       [-1,  2]])

In [181]:
data<0

array([[False, False],
       [False, False],
       [ True, False]])

In [183]:
data[data<0]=0

In [184]:
data

array([[4, 2],
       [0, 2],
       [0, 2]])

In [185]:
names

array(['Kim', 'Park', 'Lee'], dtype='<U4')

In [186]:
data

array([[4, 2],
       [0, 2],
       [0, 2]])

In [188]:
data[names=="Lee"]=999

In [189]:
data

array([[  4,   2],
       [  0,   2],
       [999, 999]])

In [193]:
arr=np.zeros((8,4))
arr
#0번 줄~ 7번 줄까지 각 줄의 모든 요소값을 줄 번호로 변경
# 0000
# 1111
# ...
# 7777

for i in range(8):
    arr[i]=i
    #[0,0,0,0] = 0 => [0,0,0,0] => [0,0,0,0]
    #[0,0,0,0] = 1 => [1,1,1,1] => [1,1,1,1]   

In [194]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])