In [1]:
gravity=[7,4,2,0,0,6,0,7,0]
gravity.reverse()

In [2]:
gravity

[0, 7, 0, 6, 0, 0, 2, 4, 7]

In [3]:

num=max(gravity)
list1=[]
for i in gravity:
    if i==0:
        list1.append([str(i)*num])
    else:
        list1.append([("1"*i)+("0"*(num-i))])
list1 # 1차 결과값, 0과 1로 수치변환

[['0000000'],
 ['1111111'],
 ['0000000'],
 ['1111110'],
 ['0000000'],
 ['0000000'],
 ['1100000'],
 ['1111000'],
 ['1111111']]

In [5]:
column_sums = [0] * len(list1[0][0])  
for row in list1:
    for i, digit in enumerate(row[0]):
        column_sums[i] += int(digit)

In [6]:
column_sums

[5, 5, 4, 4, 3, 3, 2]

In [7]:




# 결과 출력: 각 행의 열에서 0(낙차)의 갯수 구하기
for column_sum in column_sums:
    print(len(gravity)-column_sum)

4
4
5
5
6
6
7


In [8]:
gravity=[7,4,2,0,0,6,0,7,0]
# 인덱스 0번의 낙하 거리를 구하는 경우
fall_n = 1
for i in range(1, len(gravity) - 1):
    if gravity[i - 1] > gravity[i]:
        gravity[i - 1], gravity[i] = gravity[i], gravity[i - 1]
        fall_n += 1
    elif gravity[i - 1] <= gravity[i]:
        break
print(f"낙하거리 {fall_n}")

낙하거리 7


In [11]:
gravity=[7,4,2,0,0,6,0,7,0]
max_cnt=0

In [12]:
for i in range(len(gravity)-1): #0~7
    cnt=0
    for j in range(i+1, len(gravity)): #i+1 ~ 8
        if gravity[i] > gravity[j]:
            cnt+=1
    if max_cnt < cnt:
        max_cnt=cnt

In [13]:
print(max_cnt)

7


In [16]:
import random
print(random.randint(1,10))

def make_lotto():
    result = []
    for i in range(6):
        while True:
            num = random.randint(1,46)
            if num not in result:
                result.append(num)
                break
    return result

5


In [17]:
print(make_lotto())

[42, 39, 38, 23, 31, 30]


In [19]:
import numpy as np

In [20]:
arr = np.array([[0, 1, 0], [1, 2, -2], [6, 3, 2], [-1, 0, -1], [1, 0, 1]])
arr

array([[ 0,  1,  0],
       [ 1,  2, -2],
       [ 6,  3,  2],
       [-1,  0, -1],
       [ 1,  0,  1]])

In [21]:
arr.T # 전치행렬

array([[ 0,  1,  6, -1,  1],
       [ 1,  2,  3,  0,  0],
       [ 0, -2,  2, -1,  1]])

In [22]:
np.dot(arr, arr.T)

array([[ 1,  2,  3,  0,  0],
       [ 2,  9,  8,  1, -1],
       [ 3,  8, 49, -8,  8],
       [ 0,  1, -8,  2, -2],
       [ 0, -1,  8, -2,  2]])

In [23]:
arr @ arr.T

array([[ 1,  2,  3,  0,  0],
       [ 2,  9,  8,  1, -1],
       [ 3,  8, 49, -8,  8],
       [ 0,  1, -8,  2, -2],
       [ 0, -1,  8, -2,  2]])

In [ ]:
#3행2열 행렬, 2행 4열 행렬 생성(난수:1~10)
#행렬 곱셈 출력

In [37]:
arr1=np.random.randint(1,11, size=(3, 2))
arr2=np.random.randint(1,11, size=(2, 4))

In [38]:
arr1

array([[ 3,  2],
       [ 6, 10],
       [ 7,  5]])

In [39]:
arr2

array([[ 2, 10,  3,  2],
       [ 3,  3,  5,  4]])

In [40]:
arr1 @ arr2

array([[12, 36, 19, 14],
       [42, 90, 68, 52],
       [29, 85, 46, 34]])

In [41]:
np.dot(arr1,arr2)

array([[12, 36, 19, 14],
       [42, 90, 68, 52],
       [29, 85, 46, 34]])

In [ ]:
"""
선형대수학

벡터
9/6 : 사과-5, 배-2, 딸기-1
9/7 : 바나나-3, 딸기-2, 배-1
...

 사과(200)   배(100)    딸기(300)    바나나(500)
9/6     5     2       1       0
9/7     0     1       2        3

(5,2,1,0)     200    = 5*200+2*100+1*300+0*500=1500
(0,1,2,3)     100
...        @  300
(2,3,1,0)     500

...

"""

0 0 0... 200 210 255 ...
0 255 210 ...  
...
...
....






In [42]:
samples=np.random.standard_normal(size=(4,4))
samples

array([[-0.68569271, -0.5244936 ,  1.07177248, -0.61941968],
       [-0.28699581, -0.70804169,  0.98225531,  0.31658021],
       [ 0.11090721, -0.33893423,  1.33990698, -1.01119048],
       [-0.0212079 ,  0.15308405, -0.85443257,  0.18779838]])

In [43]:
np.mean(samples)

-0.05550650371709762

In [44]:
np.std(samples)

0.6897159340579999

In [45]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [ ]:
# [1.1, 2.2, 1.3, 1.4, 2.5]

In [49]:
[(x if c else y) for x, y, c in zip(xarr, yarr, cond)]

[1.1, 2.2, 1.3, 1.4, 2.5]

In [46]:
(xarr * cond) + (yarr * ~cond)

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [47]:
(xarr * cond) 

array([1.1, 0. , 1.3, 1.4, 0. ])

In [48]:
(yarr * ~cond)

array([0. , 2.2, 0. , 0. , 2.5])

In [ ]:
(xarr * cond) + (yarr * ~cond)

In [ ]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [50]:
#np.where(조건, 참, 거짓)
np.where(True, "참입니다", "거짓입니다")

array('참입니다', dtype='<U5')

In [51]:
np.where(cond, xarr, yarr)

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [52]:
arr=np.random.standard_normal((4,4))
arr
#음수 ->0, 양수 ->그대로

array([[ 4.00357348e-01, -1.46777231e+00,  7.62335489e-01,
        -3.87355826e-01],
       [-8.26343309e-01,  3.14096322e-01,  6.75579448e-04,
         8.12270130e-01],
       [ 7.74050498e-01,  9.17772791e-02, -2.70364661e+00,
         6.34177084e-01],
       [-2.47140423e-01, -1.01365201e+00, -9.97148491e-02,
        -1.65591442e+00]])

In [54]:
np.where(arr<0, 0, arr)

array([[4.00357348e-01, 0.00000000e+00, 7.62335489e-01, 0.00000000e+00],
       [0.00000000e+00, 3.14096322e-01, 6.75579448e-04, 8.12270130e-01],
       [7.74050498e-01, 9.17772791e-02, 0.00000000e+00, 6.34177084e-01],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00]])

In [57]:
import pandas as pd
import numpy as np

lst_A = {'제품':['milk','juice','bread','icecream'],
         '수량':[3,5,10,2],
         '제조일시':['2020-01-01 01:00:00','2019-12-20 15:01:00','2019-12-31 00:00:00','2020-01-02 02:03:01']}

df = pd.DataFrame(lst_A)
df
df['제조일시'] = pd.to_datetime(df['제조일시'])
df

제품  수량                제조일시
0      milk   3 2020-01-01 01:00:00
1     juice   5 2019-12-20 15:01:00
2     bread  10 2019-12-31 00:00:00
3  icecream   2 2020-01-02 02:03:01

In [ ]:
#수량이 5미만 -> 적정, 그렇지 않으면 -> 초과
#'초과여부' 열에 추가

In [60]:
df['초과여부']=np.where(df['수량']<5, '적정', '초과')

In [61]:
#df['수량']<5
df

제품  수량                제조일시 초과여부
0      milk   3 2020-01-01 01:00:00   적정
1     juice   5 2019-12-20 15:01:00   초과
2     bread  10 2019-12-31 00:00:00   초과
3  icecream   2 2020-01-02 02:03:01   적정

In [ ]:
#'제품종류'열 추가
#'제품' 열 값이 'juice' 또는 'milk' ->음료, 아니면 -> 간식

In [64]:
df['제품종류']=np.where((df['제품']=='juice') | (df['제품']=='milk'), '음료', '간식')

In [65]:
df

제품  수량                제조일시 초과여부 제품종류
0      milk   3 2020-01-01 01:00:00   적정   음료
1     juice   5 2019-12-20 15:01:00   초과   음료
2     bread  10 2019-12-31 00:00:00   초과   간식
3  icecream   2 2020-01-02 02:03:01   적정   간식

In [66]:
arr

array([[ 4.00357348e-01, -1.46777231e+00,  7.62335489e-01,
        -3.87355826e-01],
       [-8.26343309e-01,  3.14096322e-01,  6.75579448e-04,
         8.12270130e-01],
       [ 7.74050498e-01,  9.17772791e-02, -2.70364661e+00,
         6.34177084e-01],
       [-2.47140423e-01, -1.01365201e+00, -9.97148491e-02,
        -1.65591442e+00]])

In [67]:
np.mean(arr)

-0.288237501647907

In [68]:
arr.mean()

-0.288237501647907

In [69]:
np.sum(arr)

-4.611800026366512

In [70]:
arr.sum()

-4.611800026366512

In [71]:
arr

array([[ 4.00357348e-01, -1.46777231e+00,  7.62335489e-01,
        -3.87355826e-01],
       [-8.26343309e-01,  3.14096322e-01,  6.75579448e-04,
         8.12270130e-01],
       [ 7.74050498e-01,  9.17772791e-02, -2.70364661e+00,
         6.34177084e-01],
       [-2.47140423e-01, -1.01365201e+00, -9.97148491e-02,
        -1.65591442e+00]])

In [73]:
arr=np.arange(10,15)
arr.cumsum()

array([10, 21, 33, 46, 60])

In [74]:
arr=np.arange(10,16).reshape(3,2)
arr

array([[10, 11],
       [12, 13],
       [14, 15]])

In [75]:
arr.cumsum(axis=0)

array([[10, 11],
       [22, 24],
       [36, 39]])

In [76]:
arr.cumsum(axis=1)

array([[10, 21],
       [12, 25],
       [14, 29]])

In [94]:
arr.sum()
(arr>=13).sum()

arr[arr>=13].sum()

42

In [86]:
a=[[10, 11], [12, 13], [14, 15]]
a
s=0
for i in a:
    for j in i:
        if j>=13:
            s+=j

In [87]:
s

42

In [98]:
arr[1]
arr[0]
arr[2]

array([14, 15])

In [101]:
arr

array([[10, 11],
       [12, 13],
       [14, 15]])

In [102]:
brr=arr[[1,0,2]]

In [103]:
brr

array([[12, 13],
       [10, 11],
       [14, 15]])

In [104]:
brr.sort(axis=0)

In [105]:
brr

array([[10, 11],
       [12, 13],
       [14, 15]])

In [106]:
brr.sort(axis=1)

In [107]:
brr

array([[10, 11],
       [12, 13],
       [14, 15]])

In [109]:
names = np.array(["Bob", "Will", "Joe", "Bob", "Will", "Joe", "Joe"])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [110]:
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
np.unique(ints)

array([1, 2, 3, 4])

In [111]:
set(names)

{'Bob', 'Joe', 'Will'}

In [112]:
np.random.rand(3)

array([0.40091029, 0.2945383 , 0.87033713])

In [113]:
np.random.seed(20230907)

In [114]:
np.random.rand(3)

array([0.64824332, 0.27289441, 0.9663242 ])

In [115]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [126]:
np.random.seed(20230907)

In [129]:
np.random.shuffle(x)

In [130]:
x

array([9, 5, 1, 6, 7, 4, 8, 2, 0, 3])

In [141]:
np.random.choice(5, 3)

array([4, 4, 0])

In [144]:
np.random.choice(5, 3, replace=False) #  비복원 추출

array([4, 0, 2])

In [145]:
#np.random.choice(5, 10, replace=False)

ValueError: Cannot take a larger sample than population when 'replace=False'

In [146]:
np.random.choice(5, 10, replace=True)

array([0, 1, 3, 4, 1, 1, 2, 0, 4, 3])

In [147]:
np.random.choice(45, 6, replace=False)+1

array([36, 28, 22, 11,  5, 41])