In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data = {"state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
        "year": [2000, 2001, 2002, 2001, 2002, 2003],
        "pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)

In [3]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [7]:
frame.head()
frame.tail()

df=frame.head(3)
df

state  year  pop
0  Ohio  2000  1.5
1  Ohio  2001  1.7
2  Ohio  2002  3.6

In [9]:
pd.DataFrame(data, columns=['year','state','pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [11]:
frame2=pd.DataFrame(data, columns=['debt','year','state','pop'])
frame2

debt  year   state  pop
0  NaN  2000    Ohio  1.5
1  NaN  2001    Ohio  1.7
2  NaN  2002    Ohio  3.6
3  NaN  2001  Nevada  2.4
4  NaN  2002  Nevada  2.9
5  NaN  2003  Nevada  3.2

In [12]:
frame2.columns

Index(['debt', 'year', 'state', 'pop'], dtype='object')

In [14]:
frame2['state']
frame2.state

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: object

In [22]:
frame2
#1차원 : 리스트, 배열(벡터), 시리즈(벡터)
#2차원 : 리스트의리스트, 배열(행렬), 데이터프레임
type(frame2)

pandas.core.frame.DataFrame

In [24]:
frame2.loc[2]
frame2.iloc[2]
type(frame2.iloc[2])
frame2.iloc[2]

debt      NaN
year     2002
state    Ohio
pop       3.6
Name: 2, dtype: object

In [26]:
frame2['debt']=16.5
frame2

debt  year   state  pop
0  16.5  2000    Ohio  1.5
1  16.5  2001    Ohio  1.7
2  16.5  2002    Ohio  3.6
3  16.5  2001  Nevada  2.4
4  16.5  2002  Nevada  2.9
5  16.5  2003  Nevada  3.2

In [29]:
frame2['debt']=np.arange(10,16)
frame2

debt  year   state  pop
0    10  2000    Ohio  1.5
1    11  2001    Ohio  1.7
2    12  2002    Ohio  3.6
3    13  2001  Nevada  2.4
4    14  2002  Nevada  2.9
5    15  2003  Nevada  3.2

In [30]:
val = pd.Series([-1.2, -1.5, -1.7], index=["two", "four", "five"])
val

two    -1.2
four   -1.5
five   -1.7
dtype: float64

In [33]:
frame2['debt']=val
frame2

debt  year   state  pop
0   NaN  2000    Ohio  1.5
1   NaN  2001    Ohio  1.7
2   NaN  2002    Ohio  3.6
3   NaN  2001  Nevada  2.4
4   NaN  2002  Nevada  2.9
5   NaN  2003  Nevada  3.2

In [36]:
frame2['state']=='Ohio'
frame2[frame2['state']=='Ohio']

debt  year state  pop
0   NaN  2000  Ohio  1.5
1   NaN  2001  Ohio  1.7
2   NaN  2002  Ohio  3.6

In [37]:
frame2[frame2['state']=='Ohio']['year']

0    2000
1    2001
2    2002
Name: year, dtype: int64

In [39]:
frame2

debt  year   state  pop
0   NaN  2000    Ohio  1.5
1   NaN  2001    Ohio  1.7
2   NaN  2002    Ohio  3.6
3   NaN  2001  Nevada  2.4
4   NaN  2002  Nevada  2.9
5   NaN  2003  Nevada  3.2

In [38]:
frame2['state']=='Ohio'
#feature engineering(특성공학) : 파생변수를 생성
#derived variable(파생변수)

0     True
1     True
2     True
3    False
4    False
5    False
Name: state, dtype: bool

In [40]:
frame2['eastern']=frame2['state']=='Ohio'
frame2

debt  year   state  pop  eastern
0   NaN  2000    Ohio  1.5     True
1   NaN  2001    Ohio  1.7     True
2   NaN  2002    Ohio  3.6     True
3   NaN  2001  Nevada  2.4    False
4   NaN  2002  Nevada  2.9    False
5   NaN  2003  Nevada  3.2    False

In [41]:
del frame2['eastern']

In [43]:
frame2.columns

Index(['debt', 'year', 'state', 'pop'], dtype='object')

In [44]:
populations = {"Ohio": {2000: 1.5, 2001: 1.7, 2002: 3.6},
               "Nevada": {2001: 2.4, 2002: 2.9}}

In [45]:
populations

{'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}, 'Nevada': {2001: 2.4, 2002: 2.9}}

In [46]:
frame3=pd.DataFrame(populations)
frame3

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

In [51]:
#frame3.loc[0] 에러발생
#frame3.iloc[0] #묵시적 0번~
#frame3.loc[2000] 

#frame3.iloc[2]
frame3.iloc[-1]

#frame3.loc[-1] 에러발생



Ohio      3.6
Nevada    2.9
Name: 2002, dtype: float64

In [52]:
populations

{'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}, 'Nevada': {2001: 2.4, 2002: 2.9}}

In [55]:
pd.DataFrame(populations)
pd.DataFrame(populations, index=[2000,2001,2002])
pd.DataFrame(populations, index=[1999,2000,2001,2002,2003])

Ohio  Nevada
1999   NaN     NaN
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9
2003   NaN     NaN

In [56]:
frame3

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

In [61]:
pd.DataFrame({'Ohio':frame3['Ohio'][:-1],
'Nevada':frame3['Nevada'][:2]})

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4

In [63]:
frame3
frame3.to_numpy()

array([[1.5, nan],
       [1.7, 2.4],
       [3.6, 2.9]])

In [ ]:
# 파이썬-리스트,튜플,딕셔너리,집합
# 넘파이-배열(1차원(벡터),2차원(행렬),3차원...)
# 판다스-데이터프레임(2차원), 시리즈(1차원)

In [64]:
frame2

debt  year   state  pop
0   NaN  2000    Ohio  1.5
1   NaN  2001    Ohio  1.7
2   NaN  2002    Ohio  3.6
3   NaN  2001  Nevada  2.4
4   NaN  2002  Nevada  2.9
5   NaN  2003  Nevada  3.2

In [65]:
frame2.to_numpy()

array([[nan, 2000, 'Ohio', 1.5],
       [nan, 2001, 'Ohio', 1.7],
       [nan, 2002, 'Ohio', 3.6],
       [nan, 2001, 'Nevada', 2.4],
       [nan, 2002, 'Nevada', 2.9],
       [nan, 2003, 'Nevada', 3.2]], dtype=object)

In [66]:
obj = pd.Series(np.arange(3), 
                index=["a", "b", "c"])
obj

a    0
b    1
c    2
dtype: int32

In [71]:
obj.loc['a']
obj.iloc[0]
obj.loc['c']
obj.iloc[2]
obj.iloc[-1]

2

In [73]:
obj.index

Index(['a', 'b', 'c'], dtype='object')

In [74]:
obj.index[1:]

Index(['b', 'c'], dtype='object')

In [77]:
obj2=pd.Series([1.5, -2.5, 0], index=np.arange(100,103))
obj2

100    1.5
101   -2.5
102    0.0
dtype: float64

In [78]:
obj2.index

Int64Index([100, 101, 102], dtype='int64')

In [80]:
101 in obj2.index
103 in obj2.index

False

In [81]:
frame3

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

In [85]:
2003 in frame3.index
'California' in frame3.columns

False

In [86]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], 
                index=["d", "b", "a", "c"])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [87]:
obj.reindex(['a','b','c','d','e'])

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [88]:
obj3 = pd.Series(["blue", "purple", "yellow"], 
                 index=[0, 2, 4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [94]:
#obj3.reindex([0,1,2,3,4,5])
obj3.reindex(np.arange(6))
obj3.reindex(np.arange(6), method="ffill")#forward(위->아래)
obj3.reindex(np.arange(6), method="bfill")#backward(아래->위)

0      blue
1    purple
2    purple
3    yellow
4    yellow
5       NaN
dtype: object

In [ ]:
#결측값 대체 알고리즘 : ffill,bfill,보간법,회귀,knn,..

In [95]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                     index=["a", "c", "d"],
                     columns=["Ohio", "Texas", "California"])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [96]:
frame2 = frame.reindex(index=["a", "b", "c", "d"])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [97]:
obj = pd.Series(np.arange(5.), 
                index=["a", "b", "c", "d", "e"])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [98]:
new_obj = obj.drop("c")

In [99]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [100]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [101]:
obj.drop("c", inplace=True)

In [102]:
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [104]:
obj.drop(["a", "d"])

b    1.0
e    4.0
dtype: float64

In [105]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=["Ohio", "Colorado", "Utah", "New York"],
                    columns=["one", "two", "three", "four"])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [110]:
data.loc[['Colorado','Ohio']]
data['two']
data[['two','four']]

two  four
Ohio        1     3
Colorado    5     7
Utah        9    11
New York   13    15

In [112]:
data.drop(['Colorado','Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [113]:
data.drop(index=['Colorado','Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [116]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [122]:
data.drop('two', axis=1)
data.drop(['two'], axis=1)
data.drop('two', axis='columns')
data.drop(['two'], axis='columns')
data.drop(columns='two')
data.drop(columns=['two'])

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [125]:
data.drop(['one','three'], axis='columns')
data.drop(['one','three'], axis=1)

two  four
Ohio        1     3
Colorado    5     7
Utah        9    11
New York   13    15

In [126]:
obj = pd.Series(np.arange(4.), index=["a", "b", "c", "d"])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [135]:
obj['b']
obj.loc['b']
obj[1]
obj.iloc[1]
obj[2:4]
obj.iloc[2:4]
obj[[1,3]]

b    1.0
d    3.0
dtype: float64

In [138]:
obj
obj[['b', 'a','d']]
obj[[1,3]]
#obj에서 2보다 작은 데이터를 추출하시오.

b    1.0
d    3.0
dtype: float64

In [142]:
obj[obj<2]

a    0.0
b    1.0
dtype: float64

In [144]:
obj[['b','a','d']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [145]:
obj1 = pd.Series([1, 2, 3], index=[2, 0, 1])
obj2 = pd.Series([1, 2, 3], index=["a", "b", "c"])


In [149]:
obj1
obj2
obj1

2    1
0    2
1    3
dtype: int64

In [153]:
obj1.loc[1]
obj1.iloc[2]
obj1.iloc[-1]
obj1.iloc[[2,0]]


1    3
2    1
dtype: int64

In [154]:
obj2

a    1
b    2
c    3
dtype: int64

In [155]:
obj2.iloc[1:2]

b    2
dtype: int64

In [156]:
obj2.loc['b':'c']

b    2
c    3
dtype: int64

In [157]:
obj2.loc['b':'c']=99

In [158]:
obj2

a     1
b    99
c    99
dtype: int64

In [159]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=["Ohio", "Colorado", "Utah", "New York"],
                    columns=["one", "two", "three", "four"])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [160]:
data[:2]
#three 열 값이 5보다 큰 데이터를 추출하시오.

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [164]:
data['three']>5
data[data['three']>5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [165]:
data[data['three']>5]['three']

Colorado     6
Utah        10
New York    14
Name: three, dtype: int32

In [166]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [171]:
data.loc['Colorado']
data.loc['Colorado'].loc['two']
data.loc['Colorado'].loc[['two','three']]

two      5
three    6
Name: Colorado, dtype: int32

In [173]:
data.loc['Colorado', 'two']#data.loc['Colorado'].loc['two']
data.loc['Colorado', ['two','three']]

two      5
three    6
Name: Colorado, dtype: int32

In [174]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [176]:
data.iloc[[1,2]]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11

In [181]:
data.iloc[[1,2]]['four']
data.iloc[[1,2],3]
data.iloc[[1,2],[3,0]]
data.iloc[[1,2],[3,0,1]]

four  one  two
Colorado     7    4    5
Utah        11    8    9

In [182]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [187]:
data.loc['Ohio':'Utah']
data.loc[:'Utah']
data.loc[:'Utah', 'two']
data.iloc[0:3, 2]

Ohio         2
Colorado     6
Utah        10
Name: three, dtype: int32

In [188]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [190]:
data.iloc[:,:3]

one  two  three
Ohio        0    1      2
Colorado    4    5      6
Utah        8    9     10
New York   12   13     14

In [191]:
data.iloc[:,:3][data.three>5]

one  two  three
Colorado    4    5      6
Utah        8    9     10
New York   12   13     14

In [194]:
data.three>=2
data.loc[data.three>=2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [195]:
ser = pd.Series(np.arange(3.))
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [198]:
#ser[-1]
ser.iloc[-1]

2.0

In [199]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [202]:
data.loc[:,'one']
data.iloc[:,0]
data.iloc[:,0]=1

In [203]:
data

one  two  three  four
Ohio        1    1      2     3
Colorado    1    5      6     7
Utah        1    9     10    11
New York    1   13     14    15

In [204]:
data.loc[:,'one']=111
data

one  two  three  four
Ohio      111    1      2     3
Colorado  111    5      6     7
Utah      111    9     10    11
New York  111   13     14    15

In [206]:
data.iloc[2]=555
data

one  two  three  four
Ohio      111    1      2     3
Colorado  111    5      6     7
Utah      555  555    555   555
New York  111   13     14    15

In [207]:
#data 의 four 열 값이 5보다 크면 모두 100으로 변경하시오

In [211]:
data['four']
data.four
data.loc[:,'four']
data.iloc[:,3]

Ohio          3
Colorado      7
Utah        555
New York     15
Name: four, dtype: int32

In [215]:
data[data['four']>5]=100

In [216]:
data

one  two  three  four
Ohio      111    1      2     3
Colorado  100  100    100   100
Utah      100  100    100   100
New York  100  100    100   100

In [217]:
data

one  two  three  four
Ohio      111    1      2     3
Colorado  100  100    100   100
Utah      100  100    100   100
New York  100  100    100   100

In [218]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=["a", "c", "d", "e"])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],
               index=["a", "c", "e", "f", "g"])
s1
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [219]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [220]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [221]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list("bcd"),
                   index=["Ohio", "Texas", "Colorado"])
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list("bde"),
                   index=["Utah", "Ohio", "Texas", "Oregon"])
df1
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [222]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [223]:
df1+df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [224]:
df1 = pd.DataFrame({"A": [1, 2]})
df2 = pd.DataFrame({"B": [3, 4]})
df1

A
0  1
1  2

In [225]:
df2

B
0  3
1  4

In [226]:
df1+df2

A   B
0 NaN NaN
1 NaN NaN

In [227]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),
                   columns=list("abcd"))
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),
                   columns=list("abcde"))

In [228]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [229]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [241]:
df2.iloc[1]
df2.iloc[1].loc['b']
df2.iloc[1].iloc[1]
df2.iloc[1,1]
df2.iloc[1:2,1:2]

df2.loc[1,'b']
df2['b'][1]

6.0

In [242]:
df2.loc[1,'b']=np.nan

In [243]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [244]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [245]:
df1+df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [247]:
df1.add(df2)
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [248]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [249]:
1/df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [250]:
arr = np.arange(12.).reshape((3, 4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [251]:
arr[0]

array([0., 1., 2., 3.])

In [252]:
arr[0].shape

(4,)

In [253]:
arr.shape

(3, 4)

In [254]:
arr - arr[0]
#브로드캐스팅

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [255]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                     columns=list("bde"),
                     index=["Utah", "Ohio", "Texas", "Oregon"])
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [257]:
ser=frame.iloc[0]
ser

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [258]:
frame-ser

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [259]:
series2 = pd.Series(np.arange(3), index=["b", "e", "f"])
series2

b    0
e    1
f    2
dtype: int32

In [260]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [261]:
frame+series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [267]:
df=pd.read_csv("titanic/train.csv")
df
#df에서 나이(Age)가 70세 이상인 사람의 데이터를 추출하시오
df[df['Age']>=70]

PassengerId  Survived  Pclass                                  Name  \
96            97         0       1             Goldschmidt, Mr. George B   
116          117         0       3                  Connors, Mr. Patrick   
493          494         0       1               Artagaveytia, Mr. Ramon   
630          631         1       1  Barkworth, Mr. Algernon Henry Wilson   
672          673         0       2           Mitchell, Mr. Henry Michael   
745          746         0       1          Crosby, Capt. Edward Gifford   
851          852         0       3                   Svensson, Mr. Johan   

      Sex   Age  SibSp  Parch      Ticket     Fare Cabin Embarked  
96   male  71.0      0      0    PC 17754  34.6542    A5        C  
116  male  70.5      0      0      370369   7.7500   NaN        Q  
493  male  71.0      0      0    PC 17609  49.5042   NaN        C  
630  male  80.0      0      0       27042  30.0000   A23        S  
672  male  70.0      0      0  C.A. 24580  10.5000   NaN        S  
745  male  70.0      1      1   WE/P 5735  71.0000   B22        S  
851  male  74.0      0      0      347060   7.7750   NaN        S