In [ ]:
1) 문장
[[나는 사과를 좋아해], 
 [나는 바나나를 좋아해], 
 [나는 사과를 싫어해], 
 [나는 바나나를 싫어해]]

2) 문장 -> 단어
[['나는', '사과를', '좋아해'], 
 ['나는', '바나나를', '좋아해'], 
 ['나는', '사과를', '싫어해'], 
 ['나는', '바나나를', '싫어해']]

3)  문장 -> 단어 -> 수치(벡터 공간 차원)
ex) 3차원 벡터
'나는' = [0.1, 0.2, 0.9]
'사과를' = [0.3, 0.5, 0.1]
'바나나를' = [0.3, 0.5, 0.2]
'좋아해' = [0.7, 0.6, 0.5]
'싫어해' = [0.5, 0.6, 0.7]

4) 훈련 데이터(4,3,3) = (배치사이즈, 문장길이, 단어벡터차원)
[[[0.1, 0.2, 0.9], [0.3, 0.5, 0.1], [0.7, 0.6, 0.5]],
 [[0.1, 0.2, 0.9], [0.3, 0.5, 0.2], [0.7, 0.6, 0.5]],
 [[0.1, 0.2, 0.9], [0.3, 0.5, 0.1], [0.5, 0.6, 0.7]],
 [[0.1, 0.2, 0.9], [0.3, 0.5, 0.2], [0.5, 0.6, 0.7]]]

5)
* batch size = 1
1번째 배치 : 텐서의 크기? (1,3,3)
[[[0.1, 0.2, 0.9], [0.3, 0.5, 0.1], [0.7, 0.6, 0.5]]]
2번째 배치 : 텐서의 크기? (1,3,3)
[[[0.1, 0.2, 0.9], [0.3, 0.5, 0.2], [0.7, 0.6, 0.5]]]

* batch size = 2
1번째 배치 : 텐서의 크기? (2,3,3)
[[[0.1, 0.2, 0.9], [0.3, 0.5, 0.1], [0.7, 0.6, 0.5]],
 [[0.1, 0.2, 0.9], [0.3, 0.5, 0.2], [0.7, 0.6, 0.5]]]
2번째 배치 : 텐서의 크기? (2,3,3)
[[[0.1, 0.2, 0.9], [0.3, 0.5, 0.1], [0.5, 0.6, 0.7]],
 [[0.1, 0.2, 0.9], [0.3, 0.5, 0.2], [0.5, 0.6, 0.7]]]








In [1]:
import numpy as np

In [ ]:
#넘파이로 텐서를 만드는 방법

In [4]:
#1차원 텐서
t=np.array([1,2,3,4])
t
t.ndim #몇 차원 텐서
t.shape #텐서의 크기 (4,) 는 (1,4)를 의미함

(4,)

In [5]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])

In [8]:
t
t.ndim #몇 차원 텐서
t.shape #텐서의 크기 (4, 3)

(4, 3)

In [ ]:
#파이토치로 텐서를 만드는 방법

In [ ]:
#pip install torch

In [ ]:
# 클래스 : 설계도면, 붕어빵기계, 벽돌공장, ...
# 객체 : 클래스로부터 생성되는 실체
# 설계도면 -> 실제건물
# 붕어빵기계 -> 붕어빵
# 벽돌공장 -> 벽돌
# 메서드 : 객체가 수행하는 동작(기능)
# 속성(어트리뷰트) :  객체의 특성
#객체지향(적) 프로그래밍 : 
# ex) 절차지향적 사례(과거 30년 전까지)
# - 붕어빵기계로 붕어빵을 판매하던 시대가 지나가고
# 잉어빵 시대가 도래,붕어빵기계는 못쓰게 됨->잉어빵 기계 새롭게 제작
# ex) 객체지향적 사례(현재~미래)
# - 붕어빵기계로 붕어빵을 판매하던 시대가 지나가고
# 잉어빵 시대가 도래,붕어빵기계를 재사용(붕어빵기계의 메서드, 속성 중에서
#     그대로 사용할 것은 사용하고, 변경할 것은 변경, 버릴 것은 버리고)

In [9]:
import torch

In [10]:
t=torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
t
#클래스(FloatTensor) : 대문자로 시작

tensor([0., 1., 2., 3., 4., 5., 6.])

In [14]:
t.dim()
t.shape  #속성
t.size() #함수(메서드), 내차.달린다()  자동차(클래스)

#'자동차' 클래스(class)로부터 파생(생성)된 실체(객체)가 '내차'

torch.Size([7])

In [ ]:
"""
class FloatTensor:
    속성(특성)
    shape=len([0., 1., 2., 3., 4., 5., 6.])
    함수(동작)
    size():
        return len([0., 1., 2., 3., 4., 5., 6.])
    ...
"""

In [15]:
t

tensor([0., 1., 2., 3., 4., 5., 6.])

In [16]:
t[3]

tensor(3.)

In [17]:
t[2:5]

tensor([2., 3., 4.])

In [18]:
t[:3]

tensor([0., 1., 2.])

In [19]:
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                      ])

In [20]:
t

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])

In [23]:
t.dim()
t.size()
t[:,1]

tensor([ 2.,  5.,  8., 11.])

In [24]:
t[:,1].size()

torch.Size([4])

In [ ]:
행렬 연산(덧셈,뺄셈) : 두 행렬의 크기가 같아야 함
행렬 연산(곱셈)   : 두 행렬의 마지막 차원과 첫번째 차원이 일치

In [25]:
t1=torch.FloatTensor([[1,1]])
t2=torch.FloatTensor([[2,2]])

In [27]:
t1.shape
t1+t2

tensor([[3., 3.]])

In [28]:
t3=torch.FloatTensor([[1,1]]) #(1,2)
t4=torch.FloatTensor([3]) #자동 변경(브로드캐스팅) : (1,) -> (1,2)

In [29]:
t3+t4

tensor([[4., 4.]])

In [30]:
#2X1 + 1X2
t5=torch.FloatTensor([[1,3]]) #[[1,3], 
                              #[1,3]]
t6=torch.FloatTensor([[1],[3]])
#[[1],    [[1],[1],
#[3]]     [3],[3]]

In [31]:
t5.shape

torch.Size([1, 2])

In [32]:
t6.shape

torch.Size([2, 1])

In [33]:
t5+t6

tensor([[2., 4.],
        [4., 6.]])

In [34]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])

In [35]:
m1.shape

torch.Size([2, 2])

In [36]:
m2.shape

torch.Size([2, 1])

In [37]:
m1.matmul(m2)

tensor([[ 5.],
        [11.]])

In [38]:
m1*m2

tensor([[1., 2.],
        [6., 8.]])

In [41]:
t=torch.FloatTensor([[1,2],[3,4]])
t

tensor([[1., 2.],
        [3., 4.]])

In [42]:
t.mean()

tensor(2.5000)

In [43]:
t.mean(dim=0) #dim=0은 첫번째 차원, 행렬에서는 행, 행을 제거 -> 열만 남음

tensor([2., 3.])

In [44]:
t.mean(dim=1) #dim=1은 두번째 차원, 행렬에서는 열, 열을 제거 -> 행만 남음

tensor([1.5000, 3.5000])

In [45]:
t=torch.FloatTensor([[1,2],[3,4]])

In [46]:
t.sum()

tensor(10.)

In [47]:
t.sum(dim=0)

tensor([4., 6.])

In [48]:
t.sum(dim=1)

tensor([3., 7.])

In [49]:
t.sum(dim=-1) #마지막 차원 제거(열 제거)

tensor([3., 7.])

In [52]:
t

tensor([[1., 2.],
        [3., 4.]])

In [50]:
t.max()

tensor(4.)

In [51]:
t.max(dim=0) #행 제거, indices(argmax) : 최대값의 인덱스

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))

In [2]:
import numpy as np

In [4]:
import torch

In [5]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)

In [6]:
ft.shape

torch.Size([2, 2, 3])

In [7]:
ft.view([-1,3]) #view:텐서 크기 변경, 
#(-1,3)은 (?,3)로 표기하기도 함
#[2, 2, 3] 3차원 텐서를 2차원 텐서로 변경 (-1,3)
#12개 요소 구성된 3차원 텐서 -> (행:?, 열:3) => 행:4 =>(4,3)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])

In [8]:
ft.view([4,3])

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])

In [10]:
#ft.view([-1,5]) 에러
ft.view([4,-1]) 

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])

In [12]:
ft #(2,2,3) -> (?,1,3)
ft.view([-1,1,3])

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])

In [13]:
ft=torch.FloatTensor([[0],[1],[2]])
ft #3*1 행렬

tensor([[0.],
        [1.],
        [2.]])

In [14]:
ft.squeeze() #크기가 1인 차원을 제거

tensor([0., 1., 2.])

In [20]:
ft2=torch.FloatTensor([[0,1],[1,2],[2,3]])
ft2

tensor([[0., 1.],
        [1., 2.],
        [2., 3.]])

In [21]:
ft2.squeeze() #행 크기:3, 열 크기 : 2 => 크기가 1인 차원이 없으므로 제거작업 수행하지 않음

tensor([[0., 1.],
        [1., 2.],
        [2., 3.]])

In [22]:
#unsqueeze : 크기가 1인 차원을 특정 위치에 추가

In [23]:
ft = torch.Tensor([0, 1, 2])
ft

tensor([0., 1., 2.])

In [24]:
ft.unsqueeze(0) #(1,3)

tensor([[0., 1., 2.]])

In [25]:
ft.unsqueeze(1) #(3,1)

tensor([[0.],
        [1.],
        [2.]])

In [26]:
lt = torch.LongTensor([1, 2, 3, 4])
print(lt)

tensor([1, 2, 3, 4])


In [27]:
lt = torch.LongTensor([1., 2, 3, 4])
print(lt)

tensor([1, 2, 3, 4])


In [28]:
lt.float()

tensor([1., 2., 3., 4.])

In [34]:
bt2 = torch.ByteTensor([12345678901234567890, False, True, False])
#print()
print(bt2)

RuntimeError: Overflow when unpacking long

In [37]:
bt2 = torch.LongTensor([12345678901234567, False, True, False])
#print()
print(bt2)

tensor([12345678901234567,                 0,                 1,
                        0])


In [38]:
bt2 = torch.FloatTensor([12345678901234567, False, True, False])
#print()
print(bt2)

tensor([1.2346e+16, 0.0000e+00, 1.0000e+00, 0.0000e+00])


In [32]:
bt.long()

tensor([1, 0, 1, 0])

In [39]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

In [40]:
x

tensor([[1., 2.],
        [3., 4.]])

In [41]:
y

tensor([[5., 6.],
        [7., 8.]])

In [42]:
torch.cat([x,y])

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])

In [43]:
torch.cat([x,y], dim=0) #첫번째 차원을 기준으로 연결됨

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])

In [44]:
torch.cat([x,y], dim=1) #두번째 차원을 기준으로 연결됨

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])

In [45]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

In [48]:
z

tensor([3., 6.])

In [49]:
torch.stack([x, z, y])

tensor([[1., 4.],
        [3., 6.],
        [2., 5.]])

In [50]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [52]:
#텐서의 크기는 그대로 두되, 새롭게 0또는 1로 값을 채우는 것
torch.ones_like(x)
torch.zeros_like(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [53]:
x = torch.FloatTensor([[1, 2], [3, 4]])

In [54]:
x

tensor([[1., 2.],
        [3., 4.]])

In [55]:
x*2

tensor([[2., 4.],
        [6., 8.]])

In [56]:
x.mul(2)

tensor([[2., 4.],
        [6., 8.]])

In [57]:
x

tensor([[1., 2.],
        [3., 4.]])

In [58]:
x.mul_(2)

tensor([[2., 4.],
        [6., 8.]])

In [59]:
x

tensor([[2., 4.],
        [6., 8.]])

In [68]:
result = 0 #전역변수

In [69]:
def add(num):
    global result
    #result=1 # 지역변수 : 함수(블록) 내에서만 사용되는 변수
    result+=num
    print(result)
    return result

In [70]:
add(3)

3


3

In [71]:
print(result)

3


In [88]:
result1 = 0
result2 = 0

In [89]:
def add1(num):
    global result1
    result1 += num
    return result1

In [90]:
def add2(num):
    global result2
    result2 += num
    return result2

In [91]:
print(add1(3))
print(add1(4))

3
7


In [92]:
print(add2(2))
print(add2(6))

2
8


In [80]:
#print(result1)

3


In [96]:
class Calculator:
    def __init__(self): #클래스->객체 생성될때 자동 호출(생성자)
        self.result = 0
        print("생성자 호출됨")

    def add(self, num): 
        self.result += num
        print("add함수 호출됨")
        return self.result
    

In [98]:
cal1=Calculator() #클래스->객체 생성
cal2=Calculator()

생성자 호출됨
생성자 호출됨


In [99]:
cal1.add(3)

add함수 호출됨


3

In [100]:
cal1.add(4)

add함수 호출됨


7

In [101]:
cal2.add(2)

add함수 호출됨


2

In [102]:
cal2.add(6)

add함수 호출됨


8

In [116]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [193]:
torch.manual_seed(1)

In [194]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [195]:
x_train.shape

torch.Size([3, 1])

In [196]:
W=torch.zeros(1, requires_grad=True) #requires_grad=True는 W는 변수

In [197]:
b=torch.zeros(1, requires_grad=True) #requires_grad=True는 b는 변수

In [185]:
#초기 모델 가설함수 : y= 0 * x + 0
#hx=W * x_train + b

In [186]:
#hx

In [187]:
 #cost
#cost=torch.mean((hx - y_train)**2)
#cost

In [188]:
optimizer=optim.SGD([W,b],lr=0.01)

In [189]:
#optimizer.zero_grad()#미분을 해서 구한 기울기를 0으로 초기화해줌
#cost.backward() #W, b에 대한 기울기가 계산
#optimizer.step()#W,b에 대한 업데이트

In [198]:
optimizer=optim.SGD([W,b],lr=0.01)
for epoch in range(2000):
    hx=W * x_train + b
    cost=torch.mean((hx - y_train)**2)
    optimizer.zero_grad()#미분을 해서 구한 기울기를 0으로 초기화해줌
    cost.backward() #W, b에 대한 기울기가 계산
    optimizer.step()#W,b에 대한 업데이트
    if epoch%100 ==0:
        print(epoch,  W.item(), b.item(), cost.item())



0 0.18666668236255646 0.07999999821186066 18.66666603088379
100 1.7456912994384766 0.5780722498893738 0.04817060008645058
200 1.80009925365448 0.4544214904308319 0.029766537249088287
300 1.8428597450256348 0.35721680521965027 0.018393920734524727
400 1.876473307609558 0.28080499172210693 0.011366334743797779
500 1.9028971195220947 0.22073803842067719 0.007023668382316828
600 1.9236682653427124 0.1735200434923172 0.00434019835665822
700 1.9399964809417725 0.13640251755714417 0.0026819754857569933
800 1.952831506729126 0.10722480714321136 0.0016572937602177262
900 1.9629212617874146 0.0842885971069336 0.0010241125710308552
1000 1.9708527326583862 0.06625857204198837 0.0006328357267193496
1100 1.977087378501892 0.05208539217710495 0.0003910581872332841
1200 1.9819889068603516 0.04094360023736954 0.0002416476490907371
1300 1.9858416318893433 0.032185304909944534 0.00014932315389160067
1400 1.9888702630996704 0.025300635024905205 9.227206464856863e-05
1500 1.991250991821289 0.01988868787884

In [190]:
W   #W:2

tensor([1.1011], requires_grad=True)

In [184]:
b  #b:0

tensor([0.4655], requires_grad=True)

In [192]:
W.item()
b.item()

0.46550852060317993

In [199]:
W.item()*5 + b.item()

9.992821462452412

In [200]:
w = torch.tensor(2.0, requires_grad=True)


In [201]:
y=w**2

In [202]:
y

tensor(4., grad_fn=<PowBackward0>)

In [203]:
z=2*y+5

In [204]:
z

tensor(13., grad_fn=<AddBackward0>)

In [205]:
z.backward()

In [206]:
w.grad #z수식을 w로 미분한 값

tensor(8.)

In [214]:
x1_train = torch.FloatTensor([[73], [93], [89], [96], [73]])
x2_train = torch.FloatTensor([[80], [88], [91], [98], [66]])
x3_train = torch.FloatTensor([[75], [93], [90], [100], [70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [215]:
x1_train.shape

torch.Size([5, 1])

In [222]:
w1 = torch.zeros(1, requires_grad=True)
w2 = torch.zeros(1, requires_grad=True)
w3 = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

In [223]:
optimizer=optim.SGD([w1,w2,w3,b],lr=1e-5) #0.01 <= lr <= 0.001
#1* 10의 -5 승 = 1* 0.00001

for epoch in range(2000):
    hx=w1 * x1_train + w2 * x2_train+ w3 * x3_train + b
    cost=torch.mean((hx - y_train)**2)
    optimizer.zero_grad()#미분을 해서 구한 기울기를 0으로 초기화해줌
    cost.backward() #W, b에 대한 기울기가 계산
    optimizer.step()#W,b에 대한 업데이트
    if epoch%10 ==0:
        print(epoch, w1.item(), w2.item(), w3.item(), b.item(), cost.item())

0 0.29401201009750366 0.2935999929904938 0.2973800003528595 0.0034199999645352364 29661.80078125
10 0.6673623323440552 0.6653894186019897 0.6745615601539612 0.007770418655127287 1.8976879119873047
20 0.6690528392791748 0.6658924221992493 0.6757622957229614 0.007798720151185989 1.6190385818481445
30 0.6696174144744873 0.6652738451957703 0.6758250594139099 0.007813933305442333 1.6119930744171143
40 0.6701772212982178 0.6646535396575928 0.6758841276168823 0.00782909244298935 1.6049734354019165
50 0.6707355380058289 0.6640350222587585 0.6759428381919861 0.00784424040466547 1.5979907512664795
60 0.6712925434112549 0.6634181141853333 0.676001250743866 0.00785937812179327 1.5910345315933228
70 0.6718481183052063 0.6628029942512512 0.6760593056678772 0.0078745037317276 1.5841312408447266
80 0.6724023222923279 0.6621896624565125 0.6761170625686646 0.007889614440500736 1.577264428138733
90 0.6729551553726196 0.6615779995918274 0.6761744022369385 0.007904715836048126 1.5704329013824463
100 0.6735

1160 0.7248398065567017 0.6051455736160278 0.6805964112281799 0.009456190280616283 1.01512610912323
1170 0.7252631187438965 0.6046946048736572 0.6806232333183289 0.0094701386988163 1.0112825632095337
1180 0.7256854176521301 0.6042447090148926 0.680649995803833 0.00948407594114542 1.00746750831604
1190 0.7261066436767578 0.6037962436676025 0.6806762218475342 0.009498003870248795 1.0036699771881104
1200 0.7265268564224243 0.6033490300178528 0.6807023882865906 0.009511923417448997 0.999893844127655
1210 0.7269459962844849 0.6029030680656433 0.6807282567024231 0.00952583085745573 0.9961420297622681
1220 0.7273641228675842 0.6024583578109741 0.6807538866996765 0.009539728984236717 0.992401123046875
1230 0.7277812957763672 0.6020148396492004 0.6807793378829956 0.009553617797791958 0.9886852502822876
1240 0.728197455406189 0.601572573184967 0.6808045506477356 0.009567499160766602 0.9849969148635864
1250 0.7286126017570496 0.6011316180229187 0.6808295845985413 0.009581370279192924 0.9813085794

In [224]:
w1.item()*90+ w2.item()*90+ w3.item()*90 + b.item()
#예상 수능점수 : 180.9572057966143

180.9572057966143

In [231]:
#                               X1   X2    X3
x_train  =  torch.FloatTensor([[73,  80,  75], 
                               [93,  88,  93], 
                               [89,  91,  80], 
                               [96,  98,  100],   
                               [73,  66,  70]])  
y_train  =  torch.FloatTensor([[152],  [185],  [180],  [196],  [142]])

In [232]:
print(x_train.shape)
print(y_train.shape)

torch.Size([5, 3])
torch.Size([5, 1])


In [233]:
#w1 = torch.zeros(1, requires_grad=True)
#w2 = torch.zeros(1, requires_grad=True)
#w3 = torch.zeros(1, requires_grad=True)

W = torch.zeros((3,1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)

In [234]:
optimizer=optim.SGD([W,b],lr=1e-5) 

In [236]:
for epoch in range(2000):
    hx=x_train.matmul(W) + b
    cost=torch.mean((hx - y_train)**2)
    optimizer.zero_grad()#미분을 해서 구한 기울기를 0으로 초기화해줌
    cost.backward() #W, b에 대한 기울기가 계산
    optimizer.step()#W,b에 대한 업데이트
    if epoch%100 ==0:
        print(epoch, cost.item())    
        


0 9537.6943359375
100 5.752121448516846
200 5.510031700134277
300 5.2793989181518555
400 5.059759616851807
500 4.850369930267334
600 4.650723457336426
700 4.460408687591553
800 4.278825759887695
900 4.105560779571533
1000 3.940225124359131
1100 3.782344102859497
1200 3.6315715312957764
1300 3.4875869750976562
1400 3.3499629497528076
1500 3.218451738357544
1600 3.092745304107666
1700 2.9725329875946045
1800 2.8575236797332764
1900 2.7475745677948


In [237]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [238]:
torch.manual_seed(1)


In [239]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [240]:
model=nn.Linear(1,1) # 입력차원, 출력차원

In [242]:
list(model.parameters()) #w, b 값
#초기 모델 : hx=0.5153 * x_train -0.4414

[Parameter containing:
 tensor([[0.5153]], requires_grad=True),
 Parameter containing:
 tensor([-0.4414], requires_grad=True)]

In [243]:
optimizer=torch.optim.SGD(model.parameters(), lr=0.01)

In [244]:
for epoch in range(2000):
    
    hx = model(x_train) #hx=x_train.matmul(W) + b
    cost = F.mse_loss(hx, y_train)   #cost=torch.mean((hx - y_train)**2)
    
    optimizer.zero_grad()#미분을 해서 구한 기울기를 0으로 초기화해줌
    cost.backward() #W, b에 대한 기울기가 계산
    optimizer.step()#W,b에 대한 업데이트
    
    if epoch%100 ==0:
        print(epoch, cost.item())    

0 13.103541374206543
100 0.00279058120213449
200 0.00172441138420254
300 0.0010655784280970693
400 0.0006584661896340549
500 0.0004068926500622183
600 0.0002514346851967275
700 0.00015537298168055713
800 9.601024794392288e-05
900 5.9327696362743154e-05
1000 3.66610438504722e-05
1100 2.2655576685792767e-05
1200 1.3999051589053124e-05
1300 8.65114816406276e-06
1400 5.346103989722906e-06
1500 3.3032331430149497e-06
1600 2.04174443751981e-06
1700 1.2618406799447257e-06
1800 7.801028800713539e-07
1900 4.823282324650791e-07


In [245]:
list(model.parameters()) 

[Parameter containing:
 tensor([[1.9994]], requires_grad=True),
 Parameter containing:
 tensor([0.0014], requires_grad=True)]

In [246]:
new_var =  torch.FloatTensor([[4.0]]) 

In [248]:
model(new_var)

tensor([[7.9989]], grad_fn=<AddmmBackward0>)

In [249]:
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [250]:
model=nn.Linear(3,1) # 입력차원, 출력차원

In [251]:
list(model.parameters()) 

[Parameter containing:
 tensor([[-0.1119,  0.2710, -0.5435]], requires_grad=True),
 Parameter containing:
 tensor([0.3462], requires_grad=True)]

In [252]:
optimizer=torch.optim.SGD(model.parameters(), lr=1e-5)

In [253]:
for epoch in range(2000):
    
    hx = model(x_train) #hx=x_train.matmul(W) + b
    cost = F.mse_loss(hx, y_train)   #cost=torch.mean((hx - y_train)**2)
    
    optimizer.zero_grad()#미분을 해서 구한 기울기를 0으로 초기화해줌
    cost.backward() #W, b에 대한 기울기가 계산
    optimizer.step()#W,b에 대한 업데이트
    
    if epoch%100 ==0:
        print(epoch, cost.item())    

0 42134.70703125
100 5.960053443908691
200 5.654706954956055
300 5.365412712097168
400 5.091428756713867
500 4.831833839416504
600 4.585997104644775
700 4.353074550628662
800 4.132411003112793
900 3.9234554767608643
1000 3.7255024909973145
1100 3.5379719734191895
1200 3.360325574874878
1300 3.19205641746521
1400 3.0326738357543945
1500 2.881699562072754
1600 2.7386722564697266
1700 2.603201150894165
1800 2.4748456478118896
1900 2.353286027908325


In [254]:
new_var =  torch.FloatTensor([[90,90,90]]) 
model(new_var)

tensor([[181.3557]], grad_fn=<AddmmBackward0>)

In [255]:
list(model.parameters()) 

[Parameter containing:
 tensor([[0.8540, 0.8475, 0.3096]], requires_grad=True),
 Parameter containing:
 tensor([0.3568], requires_grad=True)]